version: '3'

services:

    pulmotox-mongodb:
      image: pulmotox-mongodb:1.0
      build: 
        context: ..
        dockerfile: docker/Dockerfile_mongodb
      deploy:
        restart_policy:
          condition: any
          delay: 5s
      container_name: "pulmotox-mongodb"
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: pulmotox
      ports:
        - 27017:27017
    pulmotox-mongodb-config:
      image: docker
      privileged: true
      depends_on:
          - pulmotox-mongodb
      volumes: 
          - /var/run/docker.sock:/var/run/docker.sock
      command: sh -c 'sleep 5 && docker exec pulmotox-mongodb mongorestore -h localhost:27017 --username root --password pulmoTox /mongodump-latest && docker exec pulmoTox-mongodb "pulmoTox-users-management.bash"'
    pulmotox:
        image: pulmotox-main:1.0
        build: 
            context: ..
            dockerfile: docker/Dockerfile
        deploy: 
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
        container_name: 'pulmotox'
        environment:
            CIMA_URL: "https://cima.aemps.es/cima/rest/"
            UMLS_URL: "https://uts-ws.nlm.nih.gov/rest"
            UMLS_API_KEY: "577c8f76-500d-4e94-9139-8a798bdbe78f"
            TIMEOUT: 10
            DDBB_PORT: 27017
            DDBB_URL: pulmotox_dev_tests
            DDBB_USER: 'pulmotox'
            DDBB_PASS: 'pulmotox-dev'
            DDBB_DB_NAME: "pulmotox"
            DDBB_MEDICINE_COL: "medicamento"
            DDBB_PACTIVO_COL: "principio_activo"
        volumes: 
            # - /:/ # BBDD
        command: /bin/sh -c "sleep 10; python -u main.py"